from termcolor import colored
from peakutils.peak import indexes
#from scipy.signal import find_peaks
# a="FBHJLZINOHBYTYCNCZLUYZUFIGDMZMYKVQDSPUEFJIGJPOQUFQDRJQJNTVDREXXJEOQGDUUWFWGOXQQHKJLUWFDYCMFRZTUIKVHHZPATEHKKLHUTWRLTZTQZIGEOCEIFISWNPPDQPAHSMFHXFTWNPEYSFTDSTMOYISHZSBJXLFYOGFTYYSRXOFQQRBGZSFEUVBQONIUXCSIZMFXNERJGGFJMVADTOPKWVOURJNQRDOOGYDUXKCUYEIUNIHLSPJDYYSHIZMELZQDRDQEYCWJNECKYNVDZTGSFCOPOEZXFUBWHPGQQCSQZSFTNECVGFSIBFIOJEIUDJHLRWIQAVURTPPKYECWCTUXFSOQMMVJFNVLSAFHRRMEKYPJFTQRXOJDLKCDTPXIYLRBZSBJXRMVJTOEXRIUYDUYQCVDJAMUSKMRLGJCFERYORPHQVOGOYHKUKCWNPNQXJSAZTOSYZCQGEUXJVBGUQUXJTFHZLDUTLGSKCJEIISYKLMUILGLTRIKLVGLSFMQYZCQYEIQYRFHTPXJTGOOKZOJTCCJEEIUKZBGOYHCFIYVZSFBFKSVZEVHSZBDJPCQYVCYKCXXJKVHXOJDTJOXXDXUWVOOXPBTDZBWKCNYSRZGKNMYSVPBZSFJNDSGUZNIIRMVZCVSPZBDJOJJNFBWNPTJZUMVIFUJNEUHJRFQUGFRGNISTLZGNPMFZJPHZEFHQFCNHLDAFKDDYEFDAZFRTXFDYRZWACNENCOQJWFQWEWQLTOUWUSWGTMMMRHZKXJWMKSAVPDJKICPSZEUWEQOOXBJJTVDTRFVTIAHGYEVTIOOUEPVUVCSRPUXFKKLYSUXNJHKKEFQRYOVKYEUIWCUSPBTJTWVOZOCFUSLZDFURVRDYTGXJYOGHPFDUCOBOYHMNKVXYLMBMZGOOQFYKVSOYZSHDWCUZSPIJNVRCLOJYFQRSAFJJWCUSPTINJHKXZOUNKGLSAPIXZPOKEIYXBWGODVDNHIHSPTINZGDTLMYJEHKGEEUIZQDZPTXNDGHRQUEUCOBOYHMNKVKAXBDXZVDBPGKSCWNKLDXNCRLTEIUXKFHKEXXJEHKKOBOHFAHYHIUSZAQUEFDOFMLTRJJNNWORWFQAVTRUECQQCAHYDJYXKVHHPTJUCOBKCJDYYSZUCMTGPGRSPEYXKOQIPIUXCWNKLQBFPGWGEJESYSFGYUQPVOGBLOJFXSRLPWUWPALYEBAJNSPGVFJMRHLYXFQSUAHYDJMJISUORIJZGHKKCFQGJCOAEFBDCSWSPFCGIOFKEIUJJCXXLELJIGLZJGEWNWVKXFDXRMLZTTJMVKLYPTJHFIUYPJWSFFDTNFYXKVHIFSIJFTJUOLDTNZHJRFYXKVHCTOWBYSUKHJJMNSIRJUEMVOYKYUXNJZLLPXXNTVKGOCUJEHKKEPCGFTKODWYWKIHGYEEKYWVNZOEZIWVHFUQBRZNOYHIMRRRCLQETIDOGJFHYYOWYESKYJOQJQSUYJVLYSPKWLDRTEIUXKOJKLOTYYSQODIUFIRQUXPHJZHLYLUQQVHRROCOFEWGOZUVZCZRLDPKSUOQJQVHDJWJTTGONEUQUEIYSXOIZPSJMVPLMMBDLZHZGDDEQUOQJMMQHBOQJEIUSKVHXPXQXCWJNEOEBWCUZSFVNIGWZTNUFJHUUYPCJIGKGGFWQZASYPEJMRHGGHOEKKVHAYJLJIGHZSJHYVSQHTMBNFBBKLSIFXCZNPOJMVSDXWJUXKGWGCTMJISWACOYSXCQZSFBNXVWOYUXJTCVSTDTFIYQKDTQSUWIZSBJNJBRZPOEZXVWNPZCFPVDBPEUYVQWKONOXKSUOZVIIRFNSLUJJIOWCZSAYFCWNPHBNDDVKNPDXZGWKOPVFWOLTESQIZCVOROQQWFRSOFUUJDDIPQYHBSGAACOFEOQZPODFKVDZTTIQZUKZWZRNXUHXEIQSRFHLCJWJIOWUCBDITCVZDMUXJHKGYGYAVALRWJESSIWOYDUWKOLTHBOXTOQMZCQHBAXISGQWKVHXTOJNDSDTOEYXKOQIPUXFEHKKNFBJSFDZPECZCHLHTMBNFBGUWMQWYIEHWFIURQHZPMUXTCSKUVTISCZSLOEKRFLFZOQXKOWKFOYAVFVOEZBJRRDAEIEWFTDYEVTDZBMUFSDFCBDZFSUXRWGZSFINXBDRNBCJWFRSEIUAVFBLTSIYFPMKNUINEHKKFOYAVFVKLTYYNOVKXFHLZBJUFUEKUOUQYFIXKKRNFOTWVRPOWMYTEMHGCTQKKSUZSFRNXPDTRTUJZBJZSFKSZJHXDFZZJHOORIJNEUXVPWUSKVRARIYYNOVUYMOFWOLTETYLEOOODFLJEARXPJCUFFWGYUJMRBWNPCYLSOQMMFSFLGHCPBHJDOGKZGIYRFVZFGVFERVUHFQWVUOOXQINEUDZZVHTIWJOYTQNUOVZCPDTDSUXTDXFIRHRWJIBYCZGDOEYZBYUWWUIZBWNPQHTASFZEIUXZUQGWTXTNSGAYFNUVQWKOMOHFZGZPNFJIOWACFIFERDTFOKXLOORJQHTECXTNFTBRJHCSFDFJHUUYPCJIGWXTFTYFTLMFSUTLHZNJUXJSSVZPYFQRBDZTPDBRGWNLUUQLGLBPEQWBADZEFHRRMKGGFRJVBDZHPHPZTYKCJVNVRWNLUMTLZGHPUXJWWUYEDESWWUSLUYTECIOETANERRLOBHPDOWZPSMMZQKODBIZSGWGYUYFCDDXEPVYYSXTTWUWJSWNLUIHZSQZTTJXYOYKMFUSJSDXNIYSXTRXZWUWUSFGOFINWQRTQJHRVRWNTTTNJQRBPSOIVGHXGFIYNCQUMFBUIWCKDGEWSCWNNBFYLFLTRUXJJWJTLMEKKVHLTSIYJHDXDBDIGCWKYUYFCRDXVNQYKSUIZOVNIADZTPDXRWGNLSLFIRDYESESFAHXLWYQFSECSPMFJBRZABHYFTWNPSUXVOUISUUFDQDAEJESZBJZSBJJOHUGZSTNEOUENMQNDGUKBVYWVSAZCBEWUWQGCZUAZRHTNFXJJOLJTOTJGSQJPOJYVGWYLSUSVSGKOUEAVFLLJUXJWWQJTOWXSCZSLOQLISHJTOTJGSQJPOJYVGWYLSUSVSGKOFLJEHKUFHXMZGWKLNIUVBWZHPOJRFVJZVRQVOQJESYUCSFNPDANEUWNPJHBFFNOEJIFKWPKZGJMVIQOGFHXVKHXPBBQPRRTZUASFKDTJUXNEUDHZVJGFKPGYTQNUVHYLJTYYSGODDEAVFBODMYPVHKKQJHXKGHTEFDHVWQGYFQWCMFNLQJJICIZSFXNJHRXJPVYYSFUDNEXKVLYTTDTKVLTRUXFKOVZCPDTDSUYNPKQUOFZFBBQPGHKTOVFTHLZTTQQCWQJTSUHKPDYPEESTVDTRFINEHKKHBLJCSQMEIIUICGANFTGPFDJTPINXBDRDUXJVOURJVDNMSUYPXQXUOUQLOTHFZGLTMBJUKLZSKKXKVBJCPWJEOQJSFBNLARTNFIYRFVLZSCJUHKKJFCNKHHJFMJWRJLUWFJQZUKZTOJTKVHJLSAFISDYMFJBVSQZSFCYYOWAWUHFMWRRPUBNXVWISBDLVGWNPFDJIUBYTHDFKIUKZGXDUFRMPOQYFAVHZXCFEGDOOBIYICQUXFHXCCRQPEQYRGSKNJVNTKDBPMUSXHKOQUXJISZKCFIYRFVGYEKQKFDBTPBJKZLMSUJMVMZUFMTXVSRTPTYLEOWACFYKKVHXPXUWVBRYEBHXKVHEHPKQUGHKLOEYYSUZSFOXRKDIWFQWSIWLLJDYJWJTLMIMFKLTRUXJISZKCFIYRFVVCPRFSZBSLOOTWHKKXCEBDOQYLJTKZBGOYHJMRHWXLDUXZUQGWXQXECWKLTOGVQDADFJMVALRVZMFPUDRLYOFCCQKMPERJKLZSSQIZCZGGFDTZGHZPOJMFIVGYEJNDSVRZVTJIGDOOQUYVFNACDPDEGNOLELFEQHJASELIOPZPDXSFZRMJEYWVQWUCGEWKVHTLUYTEOOYNJUSTSIUFOTFKWRTHIYHYVHRAFTKLBGZSFHJJSDXNIVNERLTRUXJZASGNUEKKVHLTSIYJHDXDJDYYOWILDEUYCQEHPKQUPHRTLUYIMLTRUEMVOUZSFVQRDRLLIKRDWQMMJHIJKLTRGHTDWQYTEUFYIUXTDQSVYXXNAOSJYLYLJTNEOQTDGLNUSRHPDQZJSWNPIYLYSQJZGJMVTUKBVUSTMWNPZMJISOUZLYSXWQODUXJJOPKLTVRIOGOZUXJRGWXZOERVFVNLEJTXCWUEIUFLGWXLMYFERHYPSJYFSVILQUNEHHXQFHJEQHZSBJBRGZNPSUYYSBOYTJFCZHJEIUNIOQZPODFJHKKJUXJEZDHZSUIKCFUYGYWDKKGEUXJPTRAYEYSGOUZMZJJJHLTRJJFXOLTDUTZDABYTHDFCGLTEIUQRPDTOJJFCZVNZXUIKVDZHIQYKVHEDQEYKSGCLTJMVSAODUUSTSRLEIUKZFVZDUQWJPRCXBDXRWG"
# a="BAEGXJJXFMBJINFVWYRYLNBGOWCUHXKVDIIREBDSUJZYWIRHBAGRSUOSIVGACXJQSIULEHBXGKZAXPXTJRFLWJDKTGLGNAHMTMPULEVNKONKVBXLAVGDUWJKYVXTQONVXRLPJIRERBFAFILMMNIUNHMNUQULEUGADCJNIPJGQVWJOTYDIISJBAWNWTYSIVCYDDKQLGPVDQINUCMLVPRGGELKNFWOSAOTQXXAKPXBPPNNHZJXIYOAHKPQDBQBMLAOWYMKJALSULARCNQBYVLFEJCCJQNXLLVHDJVBWOJZDJZANNWGWTAKTMHCQXURLPXBPLANBVNWAOEAHKYNOJDPXHXHGGRONXVXULEDBJUMTUOIELHBODLMVMPPAVRLREJYOEGHGEABCWLKUENAJJBCMLCUVAVRPBFTYUFHMAGNDVTUVZPOUGKBYTPXUWIPFCHJIVPKYSVGQHMFFLFJOTRXXAMVCULAFJALCYLXPJTJRLKJQSOOKEUBOZANASOKSJBAWRSQYVVNCYRVVRFPSMEPQBFQTZOOXRCQNDWITYTXLAZHRFSAYPQATXCZJNUCPFSGEEDCNVXVRDQHKWNISIBTPNVNVRIPNOXHCINWRRLDPARKGNDBMVBUPEVGNUBTPGSSTGNURWLVXFMNUGNDMYOOQVIPPRSUJOYMHSCPARBXNOOVEUVWONYAOSWRGCXUCNUQBRDQGQHABYSUMNIVCVQFYNFVTQONFXSJSTITJNWWXGSKULETSDOUIPCDPOUHAHCMPCCPOICXVCBPVMGLQPTLWFAKCPAVUNUNXXEFAOTQBJXTKGSMTKAPLBGVSMIDFBFQWTALBOEFSDOUTMKJVLKXNDBTBPGPNQZJWCJYRPAYWZVBBTBPGPSONHENBOSDLTJRHDAJFENQYNVTHJLYSTLAOAXYNQSKUILAVEHKJLXOSTKPRQPMVGNCSGACHWHLCIEVGNCHWILXDCTQXNHYLVSOKWJRWLFWPDFXHGZXQBHYOFRTJVBJXJZPPVCQALHWYYKUIDYERWRSNKTAENYJVLTYBFWPQAMHWHLDXEIPCARKFIVZFENVNYNIARBXCQEAHBUVXEINERRQJSPNFELYBAOMFSCPHEONWGBHVXDINVEJWRTULVXHGANYNWBCFHEONROUFZDXIEMVLDDLODNCSGYOSJHRSOKFQHAFXSQEOGTKBWVRSAYBXHTRNORSLCFRTGALHRSHXFQAKYCKJYZSOIXEHBDKQLCJRCGGQHWNOKWITTVNGCTLCDLEYPXQSZUMUMOPFFKNSLFFVPQFBLKQLQPRECENWQJJYNQAUGQHJSKCCYTUNWGBTZSOERGFCDLHHDPHEEYJUJYPFFWBGGCHAYVBFEDNVTHKFKRFQIPTFDHYOKOFAFSJXUPUOSPEPTCKJXDOBPLMAXZJSKPPVLCPTROFTYSIOTVPLWFSYSIFHRLWRALGBCOHFJBRSNSUQAVGNUBGBDBLEOVCVJQZYBQAVGNUXKOYXCOWHBHRYZDZPECAMONSNDIERGGNFQSPMBPLAGFRMNMPFVEPGCKRSNCUVYRHCWRSNCPQEREXVNTUCDVEGACKXZNRBRDVUNBVNEDIIMURUYNXBZQVEVGHTDNJUMCTJVBKJXTEDLTQQXZRYODIITKZNFXSZDSEIPGBZNHSKJQTQSNHUNUDIIDKTRWJQHQFAEFBWWQFCOUMMGGXFXRWYTILGGCHAXHXETOUGCKNRHXZQOTRVXLMSOTWPCLYRBYHQFAHCGFLCMHVMXHGOJQTXRSOHAUBAWJQVCJRGQHAPXSLIULEURMDHXZYXIBNNBWJKLGFQAKYBZNIVXULAXRCLVJAYUELMFXZNYLHUAEFBWWQFCOUMMGGXWNCADPWPGPRIRHWOPTLGFXZNZWNBXEQHAIJHLLPSKUGJWDXDOESNVUJYNYPWFXOYERWNJZCBCSUBFHKQVQJQLGFBLWYLBFWTGQKBCMLCVTETSRFRFSBFHUEGRRWTMGPVDUVNWQJHVXEYUPQDARPXHMMJBXULZSBULAPGQHPJUBFWIPJQLLMARPWEEBVPDSPMBXIQABRLHBBCPOIFCHGYZDXIEVFNPJNSCBPLVUNVNNUDFVSVVCLJQJYNQUPVZXNXKYULEAENDUQFBFJLGPCVDULBCVEXVCBCMHDXSUNQVDTJAGBMNREXXMTYNPXHGLSXBYYOGPEEGYRXWSITXYNVIHMBYSUMNIGQDCILCQIRCGNOHXLOLWAEYNDAJYPPVMKEJWQJYDIMNMGQHUFADFVCNVEHCMVWQWOPJARCJSKTXMQACKRSARFRYVZJJJEPXFXHCGLRWXAKOXDKTRWJQBZEETGFJICJYKEEYENWENLPXUSFGRUORPLKTLOTGBWXWFPPPLQJRWOTYKNSNVUJQMNACBROXRUKNBHCSMGJGCRBJLDIIBKGBDBUHBUSFCYJUPJYGISLGGQHFTYNTROYSUBRSNDIVOWTQRDWKSHMTCYYLYJZOULETZXUNTYVFWSVRWGCTYOTIMDYNSJWACPJBKTPHAZUSUWPGEQDYXLFFRFCZRORFYQFRRGFKXCXAYSMEUNWGWTCOMWHCINGNKPXJXEEBWFUZZSPRSVUNBJQZYIEVGPXQEJUDJSNCYUHWLARTUUKPTKXBSYOKIUGQHLTUFFRTKBWDUGSYHAHGAHRDFKNVTANYXIRYZZPWTUNWGLTTWFRTUUXZUTUQJWTJRURWLLCUIMCVUWQWLKECOWFNQMGHMLENFSXUCMVXBWIPTUHCTWSDQOUGRPYTYDBRTYUJWNCHMUPYCENZNBYSUMNIJQHWBLBFHOKAPDUQVPULIUJALCNUQJAOPGYUNYLXEXOEBRQJBOYMINGJCHAROOSIIUGROUYOSOOTJRKHBYDODENOHBWNWPCBQOTROLCYPXHENCYXJDJHXEMFYRVXBYMSOHAPNWDUTNEFMNCANARXASOKLKGNUJWFEOMTKCARYTZOULERNADPWHZISUTPXQBYHXUARKGRQPMHCCIGWACROJLVMMKGNWHEJYOOHIPTMLPNAKMTATNPUJUOXPXAVVPKCXAKCFIPTYDAFNBBTHHEXPCMLCVRANFXURXLCPVEXRWDPWHMFJUNFXPNYPWFWSNVWNRSNCPQEVVVHBXVKSMNICJUJLYKQLFTBVDKXHVPQADFJOXRPWFENCPXQETSEUIDJNYKJEHBEQECAMHANUQQERCTADYMZYNITJVWJUNROLIRQHJFBTYSHMNCYMUJKAYGSNVUNUXFKYOPYVNYHMYVQFXHGEKBKDAOTENFCNULJUDBWIPGNUNXASOK"
# a = "BZLGLJYPDOSJHUFJWNJWNEBFVWQUWPIXUIHYEPDHMHBPWHYHPAVJQWFSHCGOCMBOUZUKLHPXVCXCOPWAJFFAOHFBTFSGBAWEROGUKLVBKDFIXSXKHVUDJOHMPVWAQCNKPPNGJHYEFBUSDKCMLUIINWELWHUKLUUASUHPZPINQJWYGRAUIHZJPALFUVPSHCCMDSCONXPUKQWNJUKNMPQNGSLZFDYFSZVTEXMSIROBOWNBHOBVKPOZOKDQSTODDLZVWMMZBYNJUKHRQNFTWXCFDQCQJFFVNCVGKJJBLGHBUJYHNBWVORCBTLOCEXJJJROBOSABBKFUCFEZOKMNDBBROHWOGURDFVXOUKLDPJJERWFIDSHPOSDKXDPOHVFLGWHAFEFOGSAQUUNBUDUAXJQUKNTUUHVFPQXRALFGTAUNSNRWMZOVUUKQQRROUVPPTCWBGXGKXZVUQWEDHCFIVTFXMSKXTUKHFXAAUWNOPIAJFLZBOUFOJLUPOOSLCJOJZJPALJQSPVUUCMRKNPHGSLLPEBUIRBFOWYCENSOGVPTWSANHGXQCPPPHTLCOBLWTPEZGSESULXOVQKQVKLFGUZBSWNJNKJGREOWOCWNLJPNUPZYKUNSTKXSUOLVUNJTRRXSRAGBUGOJXOFLUUUNSEWQFQUPPDRHMHQPMGZCDAGTVPFOULUJWDFWCFSVYGQXJULWHBQKQUQWSZAJULUIJCKIDAEFUAQCNUPQLJTHAJBWLPEUBUKLTGDDMGRTDOVUVAWUKRTCOVIQXKUZRMMFSQDTAODCBCOHVINJFVZVFZVTEBYPRMXSLAKOPATEXJMHKFPFFORCCBNLFGDDMROBJUSKLNSTRDGGOUQNJLUHAIPZFWNVQTRDGGOZOBHTFZQJDKAJFHSSHHVNPFNJTWBJAJTKHOOXNFOUBUHSAJEWCHNOORAKDRFHKXXNBZGOCWOFNTIDCGBCWOGNODBAQLNWQJXJOJDJFWAXURUFWOGNXFTFAFFQAJJBYPHBGPUJQOLWOWABUHKYSRLJQPBTZLNMJKDRASFVWQOMWOFNUXDPPQAGCDKMZELNJNNFGCIBWJQSAWTSXOEHUEFRFBQREFDSYPADEDUTPGLOBWVTFXODHUVSJLJRWCVWOGONNFUDTFGLOBRDMDBUXHLMJLSVJQUNBZGMOHBFTJOJMQVAUPQSVOFAKPWKJQCPBWOTFNDJQNTFQAGOLWJQJOFPHKMCZBWBJOHEEVBSCONTJQJGUQWOLQBWHATJNVURNTDKLYDXFKXWDULVPTFZFQNWFUWQTBACONHPQLCSNLIHLPNPHUUQWBQMTCXAUBWVTRBJODYGTCSDFJUPGLEMJJBWRWFVIGUCWSWXSFDKNJTWCDMIFPPPHFSZWQBOEHFGJMMNWFSOLPHCZBVFFBOSMOXOBQMGPUSCDTGGDVPSHVTJPAODUPSHMHFLLJYNXBBVHTJQJQPJUPHVUNJTEDUBKLOJCKBOBPBPHVUNJPIQPXBVWVBWJWBUZOLCOMDFQPUIDYGUNUIQRDBOSAUFGELOGFULPUCZJQPTUUFRVCLJQPTPPLRSXKFRWTDULGOCZPXPIBQKVINQNLGUIHTUFUNFVDQQULVUHIVLLLMBAJJBZBVVVDKAQEXOJWQUIHAKNNUPQBUSDPPUBOFFUBJPAQGNWMLWUIHKKHRLBOJHFZLFPWLIDEFULTGUXUPPYPTHSGUCWSVJOESVUUCZFPJOZPVTFVMDKUFTVWCZYGTWJHFZOCUFAUKJMMWOGCJFLVTJOGHUPALBOXTJQNQVAEPQNZUKLUFMSZVBPXHINBBLBINXFPHKMBOFGXOUKHXFCANHCPUDSMTXOFWNYUZLFPWLIDEFULTGUXLFACUPVWGDRXJFYFPSSGTXOFXYEBWLQVAXBFNCPRRUUJLVVFFERUVIJNFWRNFWVYSRLFHBTBBZUPFWCOXHJPSGTBAOWNSFVAGEKQUKNTVSLTGRUJDUSFGBEURGOROXPUKUJNLIHJMXDFUDQSSPROHLTJPXJDXUSUKHPUQWHHWSFVPPXQADKCIPVLEPVEVQRDBWPQOBGDFDSCOVITCWYWBUXHLVTNEBLUTBOSVINKFLWUFUZVJCABOLPNPBPJZMFVMPUKLASNSMOHSFISGDCKVSNSCULXJCQUKJUXRBNEVSLHCXBLURSXMERAEPWOGZSMTWAFGOLEUYGPUUZTWFNJIWEZAJULUIUQSUGNTQHYCUNDZVNFLVHEMNSSHAGPUTKSJLIHAUILUMUQWMDCUFUJNJEWUKXNQVVPXAGUHUBTWTQOCZJQCIFQFVNJYBCROFWOCULGOVCBOWKKHRLBODQEDAGTJXUHABEDFEBWTFJROURMGFUDJNNBTKVTUBLPUHGPOSQXRLGRABNRUVIJFELCTBQVXFUZFZJTSLNJUCGTHNUIHIKUBSTSJSURMCMJJHHAXIRSGUQWXRAETQVYGUQJQPUIUVWHQGVUMJHLACMYAQHBFUKLTNXJFRAMFVZVFWVURAFTHTDMNHBUCTPIIKHPWSXWJUVWGSQSQVNWFQMCNRDJDAHFQYGTKMUVCPSLLUBWVOREFMVOCWNVFIROJWLEPWUMXBJPQZVINQBOBPIDCGDXFWHWUJRUCMUWOJCITTBKDTZPZUPOJPUUQWDRWWFQAKPWSMEUPHZOGOHGVDMEVSHNMXXJWBQPVAUBWVDRVNFQAUIXOMRWHJVAJFUGOJNTUHTCJULIUNBEBVWTNFEEJDLDUFGXJUKXOBVPPHUWURYJDPVUUREQRAUBQAYIJLFAJDUOFCSNOFZAJULUIXQWOZNSFGVKOPSMOXGUKPUXAAULWHJZVPUYJFWNOEWVEPRFBZQPMHUGXCWSPQFSHPUURDMWQJONAJFKWTWFFDDUOVBLFURTBPVTFOAUWROHDUCMXYVHJOELMYFVMTWOJOGHPBWSMRPVFLUCONPJVCJOJSKUNJBUHVOLAKQAGQRBFUKLRBASHUJQIRBTDXFTWJOUZYKURFHKJTCHNWOCGGHNMMLRGBWWWHAFOGPPHMAHLCBMSHTBPJBSQOPWHVJPZUVCBCEPPHYSSDPSBSOHSXEUKNTVQHNTXJJVNTPULXFWSHUJDFIBNTXEFWRNFVZNJWCJQPTPPLVJVWTVXBSLUIQJJBJABQKMTPVSCVJMPPHDTJDPPRNFDUCDXFWRUVUHKJBYZBCJSEPLCOMWSLWHQDYCHASQKBPNHAJJWYMLTFLHYQVJUTRAJHLUCMMJBICPGRUVINJPDMPOOFVBYWEWXHFWOGSKQCBCFTDUFQNJDHWUBVPPUNJFVCJOJ"
#key="BEACNJDJFHK" #11

def encrypt():
    a = ""

def decrypt():
    a = "TAIKPZTYWMVUILOWLRFLAFIGTAHVKBUAEVPZKEGDUAJLOLRVVWSAEWAKUVLVPTJJLKDZKOHPGWHYAEULHSJWLUFIGTLAILOAHVHSHNVLPZNRELKAWLLYMRJZAHVJVTAEYVKOWOHYAKWYYEJLYPACHSHNVLTHRJZHZAKZPUAKEVZPYWYLAEVZBRWSJLFVSABRVKYLMZFPZCVFAIOKZVMTYWPTPRUAJRRLLYSFXAOEDGVUAEVAOEMGSJAEGLZVRDSLYJVLZEILZHNUHVSAIAJLCRHZVFKZLLAILOAHVHSHNVLOHSKZLOIXZLZTDGBUTRAUPNKZLZOCSYZYJLLTOCQTWUJEVUSRKDLLCSZAHVDHYGVKAJAEQVUVRDSLSDSYPNVJPZMRJZZRFLHAIFFWLRZGKHNUKLHSFFHSCPUSLSRJLHLJGZPMZDHYTFLOVSVGMAHVWHYTYGMHLCLOLPCSULTJAUAHVKVSAIKFZTVEVAHVJAOAEWHYTYEHYSZKAOEDGZALZCLSYKGOHRSGBYLZIBPDNSALRRFKWEIZHWSCAMLTYWYLAIWVUGFAUNIENLZTZYHAIFFZHSJWZZIEYTHRJKWHSKHVAEELPHLWGYOASAAHBZDPAYRKDLLCSZAHVHVZSZTPSIKQVMEOLHUTCAMLFLLBYERKAYOSAVSOXQTPSJAVUSRJLWLRFULDZFJSUUAUNNRKHZMRJZYOMWYHNULOLELJVWERFZWATWHNEEUFLSRKYVSRDPUDWJHUKCAUYOMWYPNEGCLMSWYUAJSYLPFJALDWAUKIEYHSAIYLHMFMUAOWMUKEIYYVUEVPJEZFAOELLVWIRHSHNZLPHRVYPVNFXAOEGDHUEKLOLVFDBTEFXDHTVJKLTVUALDYSZIEVFLZTZEHAEULVIEVIBPVRDLUTKGAOEMGSBMVGMDAKWYPNCSRLSLHLYIFJTHRJZHZTNGTVOEKWOOSGZHNUVLPMFKDOITZHYEJEHSLRFKPRIWNBLRJSFSYSWLDKZPZPZUABRVAZHTIMLJOCGBYIDSNLOWEHYSKSRLNWJVTAUAZAAEULVFRTVBTBASVMVLYLSDAIFTYWVZIIAZPNJLYBMVFAVNVKHZRFKLATRKWHCVUYHFKVBYIEYPASWWIYURJFMLPTFVFKZLWLRFLATYWPTAXWDHSXWULRRLLKUJAUNOJAYPSJGYHNXWYLDXJLLNRFKILLWMPLKWYZ"
    b = a
    # length
    freq = []
    for i in range(0, len(a) - 1):
        b = " " + b[:-1]
        c = 0
        for j in range(i, len(a)):
            if b[j] == a[j]:
                c += 1
        freq.append(c)
        # print(c)
    # peaks = find_peaks(freq)
    peaks = indexes(freq, thres=0.678)
    # print(freq)
    # print(peaks)
    possible_keys = []
    possible_keys.append(peaks[1] - peaks[0])
    print("[+] Possible Key Length: " + str(possible_keys[0]))
    # print(possible_keys[0])
    # print(type(possible_keys[0]))
    # key = input("Select a Key: ")
    # print(peaks)
    # print(freq)
    key = possible_keys[0]

    # ciphers
    j = 0
    ciphers = []
    p = ""
    while (j < key):
        i = j
        p = ""
        while (i < len(a)):
            # print(a[i],end=" ")
            p = p + a[i]
            i = i + key
        j += 1
        ciphers.append(p)
        # print(p)

    # frequency
    ciphers_freq = []
    for i in range(0, len(ciphers)):
        arr = [0] * 26
        p = ciphers[i]
        # i = 0
        # arr = [0] * 26
        j = 0
        while (j < len(p)):
            pos = (ord(p[j]) - 13) % 26
            arr[pos] += 1
            j += 1
        ciphers_freq.append(arr)
    # print("Ciphers: ")
    # print(ciphers_freq)

    # map of fequency
    ind = []
    for i in range(0, 26):
        ind.append(i)

    def shift_left(f, t1):
        i = 0
        while i < f:
            t2 = t1
            t1 = t2[1:len(t2)] + [t2[0]]
            i += 1
        return t1

    j = 0
    char_freq = [0.08, 0.02, 0.03, 0.04, 0.13, 0.02, 0.02, 0.06, 0.07, 0.0, 0.01, 0.04, 0.02, 0.07, 0.08, 0.02, 0.0,
                 0.06, 0.06, 0.09, 0.03, 0.01, 0.02, 0.0, 0.02, 0.0]

    freq_sums = []

    def get_key(ciphers_freq, key_len):
        guessed_key = ""
        for l in range(0, key_len):
            freq_sums = []
            for i in range(0, 26):
                shift = shift_left(i, ciphers_freq[l])
                sum = 0
                for k in range(0, 26):
                    sum += shift[k] * char_freq[k]
                freq_sums.append(sum)
            freq_max = zip(freq_sums, ind)
            freq_max = list(freq_max)
            freq_max = sorted(freq_max, reverse=True)
            # print(freq_max[0][1])
            guessed_key += chr(65 + freq_max[0][1])
        return guessed_key

    print("[+] Guessed Key: " + get_key(ciphers_freq, key))
    print("Note: Key Detection will be much accurate if the cipher is enough long")


if __name__ == "__main__":
    p = 0
    while p == 0:
#         print(colored("\033[1m"+"[+] 1. Encrypt" + "\033[1m","red"))
        print(colored("\033[1m" + "[+] 1. Decrypt" + "\033[1m","red"))
        print(colored("\033[1m" + "[+] 2. EXIT" + "\033[1m","red"))
        choice = input(colored("\033[1m" + "Choice: " + "\033[1m","blue"))
#         if choice == "1":
#             encrypt()
        if choice == "1":
            decrypt()
        elif choice == "2":
            p = 1
        else:
            print(colored("\033[1m" + "Choose according to options provided...\n" + "\033[1m","white"))
